from __future__ import annotations

import asyncio
import base64
import io
import inspect
import json
import os
import shutil
import threading
import time
from collections.abc import Callable
from dataclasses import dataclass
from pathlib import Path
from typing import Any
from urllib.parse import urlsplit

from .integrations.base import QRAuthProvider


AUTH_SNAPSHOT_DEFAULTS = {
    "status": "",
    "message": "",
    "qrcode": "",
    "platform": "",
    "username": "",
}


@dataclass(frozen=True)
class CookieEntry:
    domain: str
    include_subdomains: bool
    path: str
    secure: bool
    expires: int
    name: str
    value: str


class CookieStore:
    """Persistent Netscape cookie jar shared by integrations, yt-dlp and Chrome."""

    def __init__(self, path: Path) -> None:
        self.path = path
        self.browser_clear_path = path.with_name(
            f"{path.stem}-browser-clear.json"
        )
        self.reauth_path = path.with_name(f"{path.stem}-reauth.json")
        self._lock = threading.RLock()

    def _load_entries(self) -> list[CookieEntry]:
        if not self.path.is_file():
            return []
        entries: list[CookieEntry] = []
        for raw_line in self.path.read_text(encoding="utf-8").splitlines():
            line = raw_line
            http_only_prefix = "#HttpOnly_"
            if line.startswith(http_only_prefix):
                line = line[len(http_only_prefix) :]
            elif not line or line.startswith("#"):
                continue
            fields = line.split("\t")
            if len(fields) != 7:
                continue
            try:
                expires = int(float(fields[4] or 0))
            except ValueError:
                expires = 0
            entries.append(
                CookieEntry(
                    domain=fields[0],
                    include_subdomains=fields[1].upper() == "TRUE",
                    path=fields[2] or "/",
                    secure=fields[3].upper() == "TRUE",
                    expires=expires,
                    name=fields[5],
                    value=fields[6],
                )
            )
        return entries

    def _save_entries(self, entries: list[CookieEntry]) -> None:
        self.path.parent.mkdir(parents=True, exist_ok=True)
        lines = [
            "# Netscape HTTP Cookie File",
            "# Generated by ASR model; do not share.",
        ]
        for item in sorted(entries, key=lambda value: (value.domain, value.path, value.name)):
            if not item.name or any(
                char in item.name + item.value for char in "\t\r\n"
            ):
                continue
            lines.append(
                "\t".join(
                    [
                        item.domain,
                        "TRUE" if item.include_subdomains else "FALSE",
                        item.path,
                        "TRUE" if item.secure else "FALSE",
                        str(max(0, item.expires)),
                        item.name,
                        item.value,
                    ]
                )
            )
        temporary = self.path.with_suffix(self.path.suffix + ".tmp")
        temporary.write_text("\n".join(lines) + "\n", encoding="utf-8")
        os.chmod(temporary, 0o600)
        temporary.replace(self.path)
        os.chmod(self.path, 0o600)

    @staticmethod
    def _domain_matches(cookie_domain: str, host: str) -> bool:
        domain = cookie_domain.lstrip(".").casefold()
        host = host.casefold()
        return bool(domain) and (host == domain or host.endswith(f".{domain}"))

    def cookies_for_url(self, url: str) -> dict[str, str]:
        parts = urlsplit(url)
        now = int(time.time())
        with self._lock:
            entries = self._load_entries()
        return {
            item.name: item.value
            for item in entries
            if self._domain_matches(item.domain, parts.hostname or "")
            and (not item.secure or parts.scheme == "https")
            and (item.expires <= 0 or item.expires > now)
            and (parts.path or "/").startswith(item.path)
        }

    def merge(
        self,
        domain: str,
        cookies: dict[str, str],
        *,
        expires: int = 0,
    ) -> None:
        if not cookies:
            return
        normalized_domain = domain if domain.startswith(".") else f".{domain}"
        expiry = expires if expires > int(time.time()) else int(time.time()) + 180 * 86400
        with self._lock:
            entries = {
                (item.domain, item.path, item.name): item
                for item in self._load_entries()
            }
            for name, value in cookies.items():
                if not name or not value:
                    continue
                item = CookieEntry(
                    domain=normalized_domain,
                    include_subdomains=True,
                    path="/",
                    secure=True,
                    expires=expiry,
                    name=name,
                    value=value,
                )
                entries[(item.domain, item.path, item.name)] = item
            self._save_entries(list(entries.values()))

    def merge_playwright(self, cookies: list[dict[str, object]]) -> None:
        with self._lock:
            entries = {
                (item.domain, item.path, item.name): item
                for item in self._load_entries()
            }
            for cookie in cookies:
                domain = str(cookie.get("domain") or "")
                name = str(cookie.get("name") or "")
                value = str(cookie.get("value") or "")
                if not domain or not name or not value:
                    continue
                try:
                    expires = int(float(cookie.get("expires") or 0))
                except (TypeError, ValueError):
                    expires = 0
                item = CookieEntry(
                    domain=domain,
                    include_subdomains=domain.startswith("."),
                    path=str(cookie.get("path") or "/"),
                    secure=bool(cookie.get("secure")),
                    expires=expires,
                    name=name,
                    value=value,
                )
                entries[(item.domain, item.path, item.name)] = item
            self._save_entries(list(entries.values()))

    def playwright_cookies_for(self, url: str) -> list[dict[str, object]]:
        parts = urlsplit(url)
        host = parts.hostname or ""
        now = int(time.time())
        with self._lock:
            entries = self._load_entries()
        result: list[dict[str, object]] = []
        for item in entries:
            if not self._domain_matches(item.domain, host):
                continue
            if item.expires > 0 and item.expires <= now:
                continue
            cookie: dict[str, object] = {
                "name": item.name,
                "value": item.value,
                "domain": item.domain,
                "path": item.path,
                "secure": item.secure,
            }
            if item.expires > 0:
                cookie["expires"] = item.expires
            result.append(cookie)
        return result

    @staticmethod
    def _normalized_domain(value: str) -> str:
        return value.strip().lstrip(".").casefold()

    @classmethod
    def _domain_in_scope(cls, domain: str, scope: str) -> bool:
        domain_value = cls._normalized_domain(domain)
        scope_value = cls._normalized_domain(scope)
        return bool(domain_value and scope_value) and (
            domain_value == scope_value
            or domain_value.endswith(f".{scope_value}")
        )

    def domains(self) -> list[str]:
        now = int(time.time())
        with self._lock:
            entries = self._load_entries()
        return sorted(
            {
                self._normalized_domain(item.domain)
                for item in entries
                if item.name and (item.expires <= 0 or item.expires > now)
            }
        )

    def cookie_names_for_scopes(
        self, scopes: list[str] | tuple[str, ...]
    ) -> set[str]:
        now = int(time.time())
        with self._lock:
            entries = self._load_entries()
        return {
            item.name.casefold()
            for item in entries
            if item.name
            and (item.expires <= 0 or item.expires > now)
            and any(self._domain_in_scope(item.domain, scope) for scope in scopes)
        }

    def delete_domains(self, scopes: list[str] | tuple[str, ...]) -> list[str]:
        normalized = [self._normalized_domain(item) for item in scopes if item]
        with self._lock:
            entries = self._load_entries()
            removed = {
                self._normalized_domain(item.domain)
                for item in entries
                if any(self._domain_in_scope(item.domain, scope) for scope in normalized)
            }
            remaining = [
                item
                for item in entries
                if not any(
                    self._domain_in_scope(item.domain, scope) for scope in normalized
                )
            ]
            self._save_entries(remaining)
        return sorted(removed)

    def _load_domain_set(self, path: Path) -> set[str]:
        if not path.is_file():
            return set()
        try:
            values = json.loads(path.read_text(encoding="utf-8"))
        except (OSError, ValueError):
            return set()
        if not isinstance(values, list):
            return set()
        return {
            self._normalized_domain(str(item))
            for item in values
            if self._normalized_domain(str(item))
        }

    def _save_domain_set(self, path: Path, domains: set[str]) -> None:
        if not domains:
            path.unlink(missing_ok=True)
            return
        path.parent.mkdir(parents=True, exist_ok=True)
        temporary = path.with_suffix(path.suffix + ".tmp")
        temporary.write_text(
            json.dumps(sorted(domains), ensure_ascii=False), encoding="utf-8"
        )
        os.chmod(temporary, 0o600)
        temporary.replace(path)
        os.chmod(path, 0o600)

    def mark_browser_clear(self, domains: list[str] | tuple[str, ...]) -> None:
        with self._lock:
            pending = self._load_domain_set(self.browser_clear_path)
            pending.update(
                self._normalized_domain(item)
                for item in domains
                if self._normalized_domain(item)
            )
            self._save_domain_set(self.browser_clear_path, pending)

    def pending_browser_clear_domains(self) -> list[str]:
        with self._lock:
            return sorted(self._load_domain_set(self.browser_clear_path))

    def complete_browser_clear(self, domains: list[str] | tuple[str, ...]) -> None:
        completed = {self._normalized_domain(item) for item in domains}
        with self._lock:
            pending = self._load_domain_set(self.browser_clear_path)
            self._save_domain_set(self.browser_clear_path, pending - completed)

    def mark_reauth(self, domains: list[str] | tuple[str, ...]) -> None:
        with self._lock:
            pending = self._load_domain_set(self.reauth_path)
            pending.update(
                self._normalized_domain(item)
                for item in domains
                if self._normalized_domain(item)
            )
            self._save_domain_set(self.reauth_path, pending)

    def requires_reauth(self, domains: list[str] | tuple[str, ...]) -> bool:
        with self._lock:
            pending = self._load_domain_set(self.reauth_path)
        return any(
            self._domain_in_scope(item, scope)
            for item in pending
            for scope in domains
        )

    def complete_reauth(self, domains: list[str] | tuple[str, ...]) -> None:
        scopes = [self._normalized_domain(item) for item in domains]
        with self._lock:
            pending = self._load_domain_set(self.reauth_path)
            remaining = {
                item
                for item in pending
                if not any(self._domain_in_scope(item, scope) for scope in scopes)
            }
            self._save_domain_set(self.reauth_path, remaining)


@dataclass(frozen=True)
class LoginCacheEntry:
    key: str
    platform: str
    domain: str
    username: str
    scopes: tuple[str, ...]

    def public(self) -> dict[str, str]:
        return {
            "key": self.key,
            "platform": self.platform,
            "domain": self.domain,
            "username": self.username,
        }


class LoginCacheManager:
    def __init__(
        self,
        cookie_store: CookieStore,
        integrations: tuple[Any, ...],
        *,
        browser_profile_dir: Path | None = None,
    ) -> None:
        self.cookie_store = cookie_store
        self.integrations = integrations
        self.browser_profile_dir = browser_profile_dir

    def _entries(self, *, check_accounts: bool) -> list[LoginCacheEntry]:
        domains = self.cookie_store.domains()
        claimed: set[str] = set()
        entries: list[LoginCacheEntry] = []
        for integration in self.integrations:
            scopes = tuple(
                CookieStore._normalized_domain(str(item))
                for item in getattr(integration, "auth_domains", ())
                if str(item).strip()
            )
            matched = {
                domain
                for domain in domains
                if any(CookieStore._domain_in_scope(domain, scope) for scope in scopes)
            }
            if not scopes or not matched:
                continue
            claimed.update(matched)
            auth_cookie_names = {
                str(item).casefold()
                for item in getattr(integration, "auth_cookie_names", ())
            }
            if auth_cookie_names and not (
                self.cookie_store.cookie_names_for_scopes(scopes)
                & auth_cookie_names
            ):
                continue
            username = ""
            check_login = getattr(integration, "check_login", None)
            if check_accounts and callable(check_login):
                try:
                    result = check_login()
                    if getattr(result, "status", "") == "valid":
                        username = str(getattr(result, "username", "") or "")
                except Exception:
                    pass
            name = str(
                getattr(integration, "platform", "")
                or getattr(integration, "name", "")
                or scopes[0]
            )
            entries.append(
                LoginCacheEntry(
                    key=f"integration:{str(getattr(integration, 'name', name)).casefold()}",
                    platform=name,
                    domain="、".join(scopes),
                    username=username,
                    scopes=scopes,
                )
            )
        for domain in domains:
            if domain in claimed:
                continue
            entries.append(
                LoginCacheEntry(
                    key=f"domain:{domain}",
                    platform=domain,
                    domain=domain,
                    username="",
                    scopes=(domain,),
                )
            )
        return entries

    def list_entries(self) -> list[dict[str, str]]:
        return [item.public() for item in self._entries(check_accounts=True)]

    def clear(self, key: str) -> LoginCacheEntry | None:
        entry = next(
            (
                item
                for item in self._entries(check_accounts=False)
                if item.key == key
            ),
            None,
        )
        if entry is None:
            return None
        removed = self.cookie_store.delete_domains(entry.scopes)
        self.cookie_store.mark_browser_clear([*entry.scopes, *removed])
        self.cookie_store.mark_reauth(entry.scopes)
        return entry

    def clear_all(self) -> None:
        domains = tuple(self.cookie_store.domains())
        if domains:
            self.cookie_store.delete_domains(domains)
        self.cookie_store.path.unlink(missing_ok=True)
        self.cookie_store.browser_clear_path.unlink(missing_ok=True)
        self.cookie_store.reauth_path.unlink(missing_ok=True)
        scopes = tuple(
            str(domain)
            for integration in self.integrations
            for domain in getattr(integration, "auth_domains", ())
            if str(domain).strip()
        )
        if scopes:
            self.cookie_store.mark_reauth(scopes)
        if self.browser_profile_dir is not None and self.browser_profile_dir.exists():
            shutil.rmtree(self.browser_profile_dir, ignore_errors=False)


def _qrcode_data_url(url: str) -> str:
    import qrcode
    from qrcode.image.svg import SvgPathImage

    image = qrcode.make(url, image_factory=SvgPathImage)
    output = io.BytesIO()
    image.save(output)
    encoded = base64.b64encode(output.getvalue()).decode("ascii")
    return f"data:image/svg+xml;base64,{encoded}"


class AuthCoordinator:
    def __init__(
        self,
        cookie_store: CookieStore,
        *,
        poll_interval_seconds: float = 1.0,
        snapshot_writer: Callable[[int, dict[str, str]], None] | None = None,
    ) -> None:
        self.cookie_store = cookie_store
        self.poll_interval_seconds = poll_interval_seconds
        self.snapshot_writer = snapshot_writer
        self._snapshots: dict[int, dict[str, str]] = {}
        self._lock = threading.RLock()

    def _set(self, task_id: int, **values: str) -> None:
        with self._lock:
            snapshot = self._snapshots.setdefault(
                task_id,
                dict(AUTH_SNAPSHOT_DEFAULTS),
            )
            snapshot.update(values)
            published = dict(snapshot)
        if self.snapshot_writer is not None:
            self.snapshot_writer(task_id, published)

    def snapshot(self, task_id: int) -> dict[str, str]:
        with self._lock:
            return dict(
                self._snapshots.get(
                    task_id,
                    AUTH_SNAPSHOT_DEFAULTS,
                )
            )

    def set_status(
        self,
        task_id: int,
        status: str,
        message: str = "",
        *,
        platform: str = "",
        username: str = "",
    ) -> None:
        values = {"status": status, "message": message}
        if platform:
            values["platform"] = platform
        if username:
            values["username"] = username
        self._set(task_id, **values)

    def clear_platform(self, platform: str) -> None:
        with self._lock:
            for task_id, snapshot in tuple(self._snapshots.items()):
                if snapshot.get("platform", "").casefold() == platform.casefold():
                    self._snapshots[task_id] = dict(AUTH_SNAPSHOT_DEFAULTS)
                    if self.snapshot_writer is not None:
                        self.snapshot_writer(task_id, dict(AUTH_SNAPSHOT_DEFAULTS))

    def clear_all(self) -> None:
        with self._lock:
            self._snapshots.clear()

    @staticmethod
    async def _call_provider(method: Callable[..., Any], *args: Any) -> Any:
        if inspect.iscoroutinefunction(method):
            return await method(*args)
        result = await asyncio.to_thread(method, *args)
        if inspect.isawaitable(result):
            return await result
        return result

    async def login_with_qrcode(
        self,
        task_id: int,
        provider: QRAuthProvider,
        should_stop: Callable[[], bool],
    ) -> bool:
        try:
            challenge = await self._call_provider(provider.create_qrcode)
            qrcode = challenge.image_data_url or _qrcode_data_url(challenge.url)
            self._set(
                task_id,
                status="waiting_qr",
                message="请扫码登录",
                qrcode=qrcode,
                platform=provider.platform,
                username="",
            )
            while not should_stop():
                result = await self._call_provider(
                    provider.poll_qrcode, challenge
                )
                self._set(task_id, status=result.status, message=result.message)
                if result.status == "success":
                    self.cookie_store.merge(
                        result.cookie_domain,
                        result.cookies,
                        expires=result.expires,
                    )
                    self.cookie_store.complete_reauth(
                        tuple(getattr(provider, "auth_domains", ()))
                    )
                    self._set(
                        task_id,
                        status="success",
                        message=result.message or "登录成功",
                        qrcode="",
                        username=result.username,
                    )
                    return True
                if result.status in {"expired", "failed"}:
                    return False
                await asyncio.sleep(self.poll_interval_seconds)
        except Exception as exc:
            self._set(
                task_id,
                status="failed",
                message=str(exc) or "二维码登录失败",
                qrcode="",
            )
            return False
        finally:
            close = getattr(provider, "close_qrcode", None)
            if callable(close):
                try:
                    await self._call_provider(close)
                except Exception:
                    pass
        return False
